### ISSUE TITLE
Question about usage : how to force the curve to go through (0,0) 

### ISSUE THREAD

**Issue by ChinaFred** [mljs/regression-polynomial#1]
Hello 
We have to perform a polynomial regression of order 2 : Ax² + Bx + C 
we want to force C to be 0 
How can we perform this operation ? 

NB this option is available in excel 

Best regards

**Comment by maasencioh** [comment]
Hello @ChinaFred, at this moment this option doesn't exist in our package, but it is a good idea, if you are interested in implementing it we'll be happy to help you.

**Comment by santimirandarp** [comment]
It seems that the current code is actually capable of this calculation, just passing an array to the degree field.

In this specific case, for example, it would be `[1,2]`, or `[2,1]` if the data is ordered in a specific way, omitting `0`.

I'm working on this and the migration in the linked PR.

Let me know if you think it's incorrect, because I may just be confused.
